# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: EPDx
theme:
  name: material
  font:
    text: Roboto
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
repo_url: https://github.com/ocni-dtu/epdx
