name: Build JavaScript

on:
  workflow_call:

jobs:
  build:
    name: Build JavaScript
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: jetli/wasm-pack-action@v0.4.0

      - name: Build
        run: wasm-pack build --features jsbindings
