on:
  workflow_call:

jobs:
  build:
    name: Build Python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: json-schema
          path: docs/schemas/

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install Dependencies
        run: |
          pip install maturin virtualenv
          virtualenv venv
          source venv/bin/activate
          maturin develop --extras tests,code-gen --target x86_64-unknown-linux-gnu

      - name: Create Pydantic Models
        run: |
          source venv/bin/activate
          datamodel-codegen \
            --input docs/schemas/epdx.schema.json \
            --input-file-type jsonschema \
            --output packages/python/epdx/pydantic.py

#      - name: Check Format
#        run: |
#          source venv/bin/activate
#          black --check packages/python/epdx
#
#      - name: Run Tests
#        run: |
#          source venv/bin/activate
#          pytest packages/python/epdx/tests

      - name: Upload Pydantic Model
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@v3
        with:
          name: pydantic
          path: 'packages/python/epdx/pydantic.py'