name: Build Rust

on:
  workflow_call:

jobs:
  rust:
    name: Build Rust
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Tests
        run: cargo test --package epdx --target x86_64-unknown-linux-gnu

      - name: Run Export Schemas
        run: cargo run --target x86_64-unknown-linux-gnu --bin export-schema > epdx.schema.json

      - name: Upload JSON Schema
        uses: actions/upload-artifact@v4
        with:
          name: json-schema
          path: 'epdx.schema.json'
