name: "CI/CD"

on:
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  NODE_VERSION: "18.x"

permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  buildRust:
    uses: ocni-dtu/epdx/.github/workflows/rust.yaml@main

  deployJS:
    uses: ocni-dtu/epdx/.github/workflows/python.yaml@main
    needs: buildRust
    secrets:
      npm_token: ${{ secrets.NPM_TOKEN }}

  deployDocs:
    uses: ocni-dtu/epdx/.github/workflows/docs.yaml@main
    needs: buildRust

  deployPython:
    uses: ocni-dtu/epdx/.github/workflows/python.yaml@main
    needs: buildRust
    secrets:
      pypi_token: ${{ secrets.PYPI_TOKEN }}

