on:
  workflow_call:

jobs:
  deployDocs:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v2
        with:
          name: schemas
          path: docs/schemas

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install Dependencies
        run: |
          pip install maturin virtualenv
          virtualenv venv
          source venv/bin/activate
          maturin develop --extras doc,code-gen --target x86_64-unknown-linux-gnu

      - name: Create Pydantic Models
        run: |
          source venv/bin/activate
          datamodel-codegen --input docs/schemas/epdx.schema.json --input-file-type jsonschema --output packages/python/epdx/pydantic.py

      - name: Build Docs
        run: |
          source venv/bin/activate
          mkdocs build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          name: site
          path: './site'

      - name: Upload Pydantic Model
        uses: actions/upload-artifact@v3
        with:
          name: pydantic
          path: 'packages/python/epdx/pydantic.py'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2